<img src="https://www.amd.com/system/files/76826-python-logo-1260x709.jpg" height="150px">
<img src="https://miro.medium.com/max/1200/0*8GKnV4s-Ea-N0G0p.png" height="180px">

# Урок 6. NumPy

[NumPy](https://numpy.org/) - это open-source модуль для python, который предоставляет общие математические и числовые операции в виде пре-скомпилированных, быстрых функций. NumPy (Numeric Python) предоставляет базовые методы для манипуляции с большими массивами и матрицами. SciPy (Scientific Python) расширяет функционал numpy огромной коллекцией полезных алгоритмов, таких как минимизация, преобразование Фурье, регрессия, и другие прикладные математические техники.

## 1. Установка

Процесс установки зависит от того, каким пакетным менеджером вы предпочитаете пользоваться:

**PIP**

```plaine
pip install numpy
```

**CONDA**

```plain
# Best practice, use an environment rather than install in the base env
conda create -n my-env
conda activate my-env
# If you want to install from conda-forge
conda config --env --add channels conda-forge
# The actual install command
conda install numpy
```

В Google Colab `numpy` уже установлен, поэтому дополнительных телодвижений не требуется.

## 2. Подключение

Есть несколько путей импорта. Стандартный метод это — использовать простое выражение:

In [ ]:
import numpy

Тем не менее, для большого количества вызовов функций numpy, становится утомительно писать numpy.X снова и снова. Вместо этого намного легче сделать это так:

In [94]:
import numpy as np

Это выражение позволяет нам получать доступ к numpy объектам используя np.X вместо numpy.X. Также можно импортировать numpy прямо в используемое пространство имен, чтобы вообще не использовать функции через точку, а вызывать их напрямую:

In [ ]:
from numpy import *

Однако, этот вариант не приветствуется в программировании на python.

## 3. Массивы

Главной особенностью numpy является объект `array`. Массивы схожи со списками в python, исключая тот факт, что элементы массива должны иметь одинаковый тип данных, как `float` и `int`. С массивами можно проводить числовые операции с большим объемом информации в разы быстрее и, главное, намного эффективнее чем со списками.

Создание массива из списка:

In [103]:
a = np.array([1, 4, 5, 8], float)
print(a, type(a), type(a[0]))

[1. 4. 5. 8.] <class 'numpy.ndarray'> <class 'numpy.float64'>


In [104]:
b = np.array([1, 4, 5, 8], int)
print(b, type(b), type(b[0]))

[1 4 5 8] <class 'numpy.ndarray'> <class 'numpy.int64'>


Здесь функция array принимает два аргумента: список для конвертации в массив и тип для каждого элемента. Ко всем элементам можно получить доступ и манипулировать ими так же, как вы бы это делали с обычными списками:

In [105]:
print(a[:2])

[1. 4.]


In [106]:
print(a[3])

8.0


In [107]:
a[0] = 5.0
print(a)

[5. 4. 5. 8.]


Массивы могут быть и многомерными. В отличии от списков можно использовать запятые в скобках. Вот пример двумерного массива (матрица):

In [108]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
print(a)

[[1. 2. 3.]
 [4. 5. 6.]]


In [109]:
print(a[0,0])

1.0


In [111]:
print(a[0,1])

2.0


Array slicing работает с многомерными массивами аналогично, как и с одномерными, применяя каждый срез, как фильтр для установленного измерения. Используйте ":" в измерении для указывания использования всех элементов этого измерения:

In [112]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
print(a)

[[1. 2. 3.]
 [4. 5. 6.]]


In [113]:
print(a[1,:])

[4. 5. 6.]


In [114]:
print(a[:,2])

[3. 6.]


In [117]:
print(a[-1:, -2:])

[[5. 6.]]


Метод shape возвращает количество строк и столбцов в матрице:

In [119]:
print(a.shape)

(2, 3)


Метод dtype возвращает тип переменных, хранящихся в массиве:

In [120]:
print(a.dtype)

float64


Тут float64, это числовой тип данных в numpy, который используется для хранения вещественных чисел двойной точности. Так же как float в Python.

Метод len возвращает длину первого измерения (оси):

In [122]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
print(len(a))

2


Метод in используется для проверки на наличие элемента в массиве:

In [123]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
print(2 in a)
print(0 in a)

True
False


Массивы можно переформировать при помощи метода, который задает новый многомерный массив. Следуя следующему примеру, мы переформатируем одномерный массив из десяти элементов во двумерный массив, состоящий из пяти строк и двух столбцов:

In [29]:
a = np.array(range(10), float)
print(a)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [30]:
a = a.reshape((5, 2))
print(a)

[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]


In [31]:
a.shape

(5, 2)

Обратите внимание, метод reshape создает новый массив, а не модифицирует оригинальный.

Имейте ввиду, связывание имен в python работает и с массивами. Метод copy используется для создания копии существующего массива в памяти:

In [124]:
a = np.array([1, 2, 3], float)
b = a
c = a.copy()
a[0] = 0
print(a)
print(b)
print(c)

[0. 2. 3.]
[0. 2. 3.]
[1. 2. 3.]


Списки можно тоже создавать с массивов:

In [36]:
a = np.array([1, 2, 3], float)
print(a)
print(a.tolist())
print(list(a))    # или так

[1. 2. 3.]
[1.0, 2.0, 3.0]
[1.0, 2.0, 3.0]


Можно также переконвертировать массив в бинарную строку (то есть, не human-readable форму). Используйте метод tostring для этого. Метод fromstring работает в для обратного преобразования. Эти операции иногда полезны для сохранения большого количества данных в файлах, которые могут быть считаны в будущем.

In [38]:
a = np.array([1, 2, 3], float)
s = a.tostring()
print(s)

b'\x00\x00\x00\x00\x00\x00\xf0?\x00\x00\x00\x00\x00\x00\x00@\x00\x00\x00\x00\x00\x00\x08@'


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
  


In [39]:
print(np.fromstring(s))

[1. 2. 3.]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  """Entry point for launching an IPython kernel.


Заполнение массива одинаковым значением.

In [41]:
a = np.array([1, 2, 3], float)
print(a)
a.fill(0)
print(a)

[1. 2. 3.]
[0. 0. 0.]


Транспонирование массивов также возможно, при этом создается новый массив:

In [44]:
a = np.array(range(6), float).reshape((2, 3))
print(a, '\n')
print(a.transpose())

[[0. 1. 2.]
 [3. 4. 5.]] 

[[0. 3.]
 [1. 4.]
 [2. 5.]]


Многомерный массив можно переконвертировать в одномерный при помощи метода flatten:

In [45]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
print(a, '\n')
print(a.flatten())

[[1. 2. 3.]
 [4. 5. 6.]] 

[1. 2. 3. 4. 5. 6.]


Два или больше массивов можно сконкатенировать при помощи метода concatenate:

In [125]:
a = np.array([1,2], float)
b = np.array([3,4,5,6], float)
c = np.array([7,8,9], float)
print(np.concatenate((a, b, c)))

[1. 2. 3. 4. 5. 6. 7. 8. 9.]


Если массив не одномерный, можно задать ось, по которой будет происходить соединение. По умолчанию (не задавая значения оси), соединение будет происходить по первому измерению:

In [126]:
a = np.array([[1, 2], [3, 4]], float)
b = np.array([[5, 6], [7,8]], float)
print(np.concatenate((a,b)))

[[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]


In [127]:
print(np.concatenate((a,b), axis=0))

[[1. 2.]
 [3. 4.]
 [5. 6.]
 [7. 8.]]


In [130]:
print(np.concatenate((a,b), axis=1))

[[1. 2. 5. 6.]
 [3. 4. 7. 8.]]


В заключении, размерность массива может быть увеличена при использовании константы `newaxis` в квадратных скобках:

In [136]:
a = np.array([1, 2, 3], float)
print(a)

[1. 2. 3.]


In [137]:
print(a[:,np.newaxis])

[[1.]
 [2.]
 [3.]]


In [57]:
print(a[:,np.newaxis].shape)

(3, 1)


In [59]:
print(a[np.newaxis,:])

[[1. 2. 3.]]


In [60]:
print(a[np.newaxis,:].shape)

(1, 3)


Заметьте, тут каждый массив двумерный; созданный при помощи newaxis имеет размерность один. Метод newaxis подходит для удобного создания надлежаще-мерных массивов в векторной и матричной математике.

## 4. Другие пути создания массивов

Функция arange аналогична функции range, но возвращает массив:

In [139]:
print(np.arange(5, dtype=float))

[0. 1. 2. 3. 4.]


In [140]:
print(np.arange(1, 6, 2, dtype=int))

[1 3 5]


Функции zeros и ones создают новые массивы с установленной размерностью, заполненные этими значениями. Это, наверное, самые простые в использовании функции для создания массивов:

In [63]:
print(np.ones((2,3), dtype=float))

[[1. 1. 1.]
 [1. 1. 1.]]


In [64]:
print(np.zeros(7, dtype=int))

[0 0 0 0 0 0 0]


Функции zeros_like и ones_like могут преобразовать уже созданный массив, заполнив его нулями и единицами соответственно:

In [65]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
print(np.zeros_like(a))

[[0. 0. 0.]
 [0. 0. 0.]]


In [66]:
print(np.ones_like(a))

[[1. 1. 1.]
 [1. 1. 1.]]


Также есть некоторое количество функций для создания специальных матриц. Для создания квадратной матрицы с главной диагональю, которая заполненная единицами, воспользуемся методом identity:

In [67]:
print(np.identity(4, dtype=float))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Функция eye возвращает матрицу с единичками на к-атой диагонали:

In [142]:
print(np.eye(4, k=1, dtype=float))

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


## 5. Математические операции над массивами

Когда для массивов мы используем стандартные математические операции, должен соблюдаться принцип: элемент--элемент. Это означает, что массивы должны быть одинакового размера во время сложения, вычитания и тому подобных операций:

In [145]:
a = np.array([1,2,3], float)
b = np.array([5,2,6], float)
print(a,'\n')
print(b)

[1. 2. 3.] 

[5. 2. 6.]


In [70]:
print(a + b)

[6. 4. 9.]


In [73]:
print(a - b)

[-4.  0. -3.]


In [72]:
print(a * b)

[ 5.  4. 18.]


In [74]:
print(b / a)

[5. 1. 2.]


In [75]:
print(a % b)

[1. 0. 3.]


In [146]:
print(b**a)

[  5.   4. 216.]


Для двухмерных массивов, умножение остается поэлементным и не соответствует умножению матриц. Для этого существуют специальные функции, которые мы изучим позже.

In [147]:
a = np.array([[1,2], [3,4]], float)
b = np.array([[2,0], [1,3]], float)
print(a * b)

[[ 2.  0.]
 [ 3. 12.]]


При несоответствии в размере выбрасываются ошибки:

In [78]:
a = np.array([1,2,3], float)
b = np.array([4,5], float)
a + b

ValueError: ignored

Однако, если размерность массивов не совпадает, они будут преобразованы для выполнения математических операций. Это зачастую означает, что меньший массив будет использован несколько раз для завершения операций. Рассмотрим такой пример:

In [148]:
a = np.array([[1, 2], [3, 4], [5, 6]], float)
b = np.array([-1, 3], float)
print(a, '\n\n', b)

[[1. 2.]
 [3. 4.]
 [5. 6.]] 

 [-1.  3.]


In [80]:
print(a + b)

[[0. 5.]
 [2. 7.]
 [4. 9.]]


Тут, одномерный массив b был преобразован в двухмерный, который соответствует размеру массива a. По существу, b был повторен несколько раз, для каждой «строки» a. Иначе его можно представить так:

In [ ]:
array([[-1.,  3.],
       [-1.,  3.],
       [-1.,  3.]])

Python автоматически преобразовывает массивы в этом случае. Иногда, однако, когда преобразование играет роль, мы можем использовать константу newaxis, чтобы изменить преобразование:

In [84]:
a = np.zeros((2,2), float)
b = np.array([-1., 3.], float)
print(a, '\n\n', b)

[[0. 0.]
 [0. 0.]] 

 [-1.  3.]


In [85]:
print(a + b)

[[-1.  3.]
 [-1.  3.]]


In [86]:
print(a + b[np.newaxis,:])

[[-1.  3.]
 [-1.  3.]]


In [87]:
print(a + b[:,np.newaxis])

[[-1. -1.]
 [ 3.  3.]]


Вдобавок к стандартным операторам, в numpy включена библиотека стандартных математических функций, которые могут быть применены поэлементно к массивам. Собственно функции: abs, sign, sqrt, log, log10, exp, sin, cos, tan, arcsin, arccos, arctan, sinh, cosh, tanh, arcsinh, arccosh, и arctanh.

In [88]:
a = np.array([1, 4, 9], float)
print(np.sqrt(a))

[1. 2. 3.]


Функции floor, ceil и rint возвращают нижние, верхние или ближайшие (округлённое) значение:

In [89]:
a = np.array([1.1, 1.5, 1.9], float)
print(np.floor(a))

[1. 1. 1.]


In [90]:
print(np.ceil(a))

[2. 2. 2.]


In [91]:
print(np.rint(a))

[1. 2. 2.]


Также в numpy включены две важные математические константы:

In [149]:
print(np.pi)
print(np.e)

3.141592653589793
2.718281828459045


## 6. Перебор элементов массива

Проводить итерацию массивов можно аналогично спискам:

In [150]:
a = np.array([1, 4, 5], int)
for x in a:
  print(x)

1
4
5


Для многомерных массивов итерация будет проводиться по первой оси, так, что каждый проход цикла будет возвращать «строку» массива:

In [152]:
a = np.array([[1, 2], [3, 4], [5, 6]], float)
for x in a:
  print(x)

[1. 2.]
[3. 4.]
[5. 6.]


Множественное присваивание также доступно при итерации:

In [153]:
a = np.array([[1, 2], [3, 4], [5, 6]], float)
for (x, y) in a:
  print(x * y)

2.0
12.0
30.0


## 7. Базовые операции над массивами

Для получения каких-либо свойств массивов существует много функций. Элементы могут быть суммированы или перемножены:

In [154]:
a = np.array([2, 4, 3], float)
a.sum()

9.0

In [155]:
a.prod()

24.0

В этом примере были использованы функции массива. Также можно использовать собственные функции numpy:

In [156]:
np.sum(a)

9.0

In [157]:
np.prod(a)

24.0

Для большинства случаев могут использоваться оба варианта.
Некие функции дают возможность оперировать статистическими данными. Это функции mean (среднее арифметическое), вариация и девиация:

In [161]:
a = np.array([2, 1, 9], float)
a.mean()

4.0

In [162]:
a.var()

12.666666666666666

In [163]:
a.std()

3.559026084010437

Можно найти минимум и максимум в массиве:

In [164]:
a = np.array([2, 1, 9], float)
print(a.min(), a.max())

1.0 9.0


Функции argmin и argmax возвращают индекс минимального или максимального элемента:

In [165]:
a = np.array([2, 1, 9], float)
print(a.argmin(), a.argmax())

1 2


Для многомерных массивов каждая из функций может принять дополнительный аргумент axis и в зависимости от его значения выполнять функции по определенной оси, помещая результаты исполнения в массив:

In [166]:
a = np.array([[0, 2], [3, -1], [3, 5]], float)
a.mean(axis=0)

array([2., 2.])

In [167]:
print(a.mean(axis=1))

[1. 1. 4.]


In [168]:
a.min(axis=1)

array([ 0., -1.,  3.])

In [169]:
a.max(axis=0)

array([3., 5.])

Как и списки, массивы можно отсортировать:

In [170]:
a = np.array([6, 2, 5, -1, 0], float)
sorted(a)

[-1.0, 0.0, 2.0, 5.0, 6.0]

In [175]:
a.sort()
print(a)

[1. 1. 4. 5. 5. 5. 7.]


Значения в массиве могут быть «сокращены», чтобы принадлежать заданному диапазону. Это тоже самое что применять min(max(x, minval), maxval) к каждому элементу x:

In [177]:
a = np.array([6, 2, 5, -1, 0], float)
a.clip(0, 5)

array([5., 2., 5., 0., 0.])

Уникальные элементы могут быть извлечены вот так:

In [178]:
a = np.array([1, 1, 4, 5, 5, 5, 7], float)
np.unique(a)

array([1., 4., 5., 7.])

Для двухмерных массивов диагональ можно получить так:

In [179]:
a = np.array([[1, 2], [3, 4]], float)
a.diagonal()

array([1., 4.])

## 8. Операторы сравнения и тестирование значений

Булево сравнение может быть использовано для поэлементного сравнения массивов одинаковых длин. Возвращаемое значение это массив булевых True/False значений:

In [188]:
a = np.array([1, 3, 0], float)
b = np.array([0, 3, 2], float)
print(a > b, (a > b).dtype)

[ True False False] bool


In [189]:
print(a == b, (a == b).dtype)

[False  True False] bool


In [190]:
print(a <= b, (a <= b).dtype)

[False  True  True] bool


Результат сравнения может быть сохранен в массиве:

In [191]:
c = a > b
c

array([ True, False, False])

Массивы могут быть сравнены с одиночным значением:

In [192]:
a = np.array([1, 3, 0], float)
a > 2

array([False,  True, False])

Операторы any и all могут быть использованы для определения истинны ли хотя бы один или все элементы соответственно:

In [194]:
c = np.array([ True, False, False], bool)
print('any =', any(c), ' all =', all(c))

any = True  all = False


Комбинированные булевы выражения могут быть применены к массивам по принципу элемент — элемент используя специальные функции logical_and, logical_or и logical_not:

In [195]:
a = np.array([1, 3, 0], float)
np.logical_and(a > 0, a < 3)

array([ True, False, False])

In [196]:
b = np.array([True, False, True], bool)
np.logical_not(b)

array([False,  True, False])

In [197]:
c = np.array([False, True, False], bool)
np.logical_or(b, c)

array([ True,  True,  True])

Функция where создает новый массив из двух других массивов одинаковых длин используя булев фильтр для выбора межу двумя элементами. Базовый синтаксис: where(boolarray,
truearray, falsearray):

In [251]:
a = np.array([1, 3, -4], float)
np.where(a < 0, -a, a)

array([1., 3., 4.])

С функцией where так же может быть реализовано «массовое сравнение»:

In [200]:
print(np.where(a > 0, 3, 2))

[3 3 2]


Некоторые функции дают возможность тестировать значения в массиве. Функция nonzero возвращает кортеж индексов ненулевых значений. Количество элементов в кортеже равно количеству осей в массиве:

In [204]:
a = np.array([[0, 1], [3, 0]], float)
a.nonzero()

(array([0, 1]), array([1, 0]))

Также можно проверить значения на конечность и NaN(not a number):

In [208]:
a = np.array([1, np.NaN, np.Inf], float)
print(a)

[ 1. nan inf]


In [209]:
np.isnan(a)

array([False,  True, False])

In [210]:
np.isfinite(a)

array([ True, False, False])

Хотя здесь мы использовали константы numpy чтобы добавить значения NaN и бесконечность, они могут быть результатами применения стандартных математических операций.

## 9. Выбор элементов массива и манипуляция с ними

Мы уже видели, как и у списков, элементы массива можно получить используя операцию доступа по индексу. Однако, в отличии от списков, массивы также позволяют делать выбор элементов используя другие массивы. Это значит, что мы можем использовать массив для фильтрации специфических подмножеств элементов других массивов.

Булевы массивы могут быть использованы как массивы для фильтрации:

In [211]:
a = np.array([[6, 4], [5, 9]], float)
a >= 6

array([[ True, False],
       [False,  True]])

In [214]:
a[a >= 6]

array([6., 9.])

Стоит заметить, что когда мы передаем булев массив a>=6 как индекс для операции доступа по индексу массива a, возвращаемый массив будет хранить только True значения. Также мы можем записать массив для фильтрации в переменную:

In [256]:
a = np.array([[6, 4], [5, 9]], float)
sel = (a >= 6)
a[sel]

array([6., 9.])

Более замысловатая фильтрация может быть достигнута использованием булевых выражений:

In [218]:
a[np.logical_and(a > 5, a < 9)]

array([6.])

В придачу к булеву выбору, также можно использовать целочисленные массивы. В этом случае, целочисленный массив хранит индексы элементов, которые будут взяты из массива. Рассмотрим следующий одномерный пример:

In [219]:
a = np.array([2, 4, 6, 8], float)
b = np.array([0, 0, 1, 3, 2, 1], int)
a[b]

array([2., 2., 4., 8., 6., 4.])

Иными словами, когда мы используем b для получения элементов из a, мы берем 0-й, 0-й, 1-й, 3-й, 2-й и 1-й элементы a в этом порядке. Списки также могут быть использованы как массивы для фильтрации:

In [220]:
a = np.array([2, 4, 6, 8], float)
a[[0, 0, 1, 3, 2, 1]]

array([2., 2., 4., 8., 6., 4.])

Для многомерных массивов, нам необходимо передать несколько одномерных целочисленных массивов в оператор доступа индексу для каждой оси. Потом каждый из массивов проходит такую последовательность: первый элемент соответствует индексу строки, который является первым элементом массива b, второй элемент соответствует индексу столбца, который является первым элементом массива c и так далее. Пример:

In [221]:
a = np.array([[1, 4], [9, 16]], float)
b = np.array([0, 0, 1, 1, 0], int)
c = np.array([0, 1, 1, 1, 1], int)
a[b,c]

array([ 1.,  4., 16., 16.,  4.])

Специальная функция take доступна для выполнения выборки с целочисленными массивами. Это работает также как и использования оператора взятия по индексу:

In [222]:
a = np.array([2, 4, 6, 8], float)
b = np.array([0, 0, 1, 3, 2, 1], int)
a.take(b)

array([2., 2., 4., 8., 6., 4.])

Функция take также предоставляет аргумент axis (ось) для взятия подсекции многомерного массива вдоль какой-либо оси. (Прим. переводчика: по строкам или столбцам (для двумерных массивов)).

In [223]:
a = np.array([[0, 1], [2, 3]], float)
b = np.array([0, 0, 1], int)
a.take(b, axis=0)

array([[0., 1.],
       [0., 1.],
       [2., 3.]])

In [224]:
a.take(b, axis=1)

array([[0., 0., 1.],
       [2., 2., 3.]])

В противоположность к функции take есть функция put, которая будет брать значения из исходного массива и записывать их на специфические индексы в другом put-массиве.

In [225]:
a = np.array([0, 1, 2, 3, 4, 5], float)
b = np.array([9, 8, 7], float)
a.put([0, 3], b)
a

array([9., 1., 2., 8., 4., 5.])

Заметим, что значение 7 из исходного массива b не было использовано, так как только 2 индекса [0, 3] указаны. Исходный массив будет повторен если необходимо в случае не соответствия длин:

In [226]:
a = np.array([0, 1, 2, 3, 4, 5], float)
a.put([0, 3], 5)
a

array([5., 1., 2., 5., 4., 5.])

## 10. Векторная и матричная математика

NumPy обеспечивает много функций для работы с векторами и матрицами. Функция dot возвращает скалярное произведение векторов:

In [227]:
a = np.array([1, 2, 3], float)
b = np.array([0, 1, 1], float)
np.dot(a, b)

5.0

Функция dot также может умножать матрицы:

In [234]:
a = np.array([[0, 1], [2, 3]], float)
b = np.array([2, 3], float)
c = np.array([[1, 1], [4, 0]], float)
print(a, '\n')
print(b, '\n')
print(c)

[[0. 1.]
 [2. 3.]] 

[2. 3.] 

[[1. 1.]
 [4. 0.]]


In [230]:
np.dot(b, a)

array([ 6., 11.])

In [231]:
np.dot(a, b)

array([ 3., 13.])

In [232]:
np.dot(a, c)

array([[ 4.,  0.],
       [14.,  2.]])

In [233]:
np.dot(c, a)

array([[2., 4.],
       [0., 4.]])

Также можно получить скалярное, тензорное и внешнее произведение матриц и векторов. Заметим, что для векторов внутреннее и скалярное произведение совпадает.

In [235]:
a = np.array([1, 4, 0], float)
b = np.array([2, 2, 1], float)
np.outer(a, b)

array([[2., 2., 1.],
       [8., 8., 4.],
       [0., 0., 0.]])

In [239]:
np.inner(a, b)


10.0

In [237]:
np.cross(a, b)

array([ 4., -1., -6.])

NumPy также предоставляет набор встроенных функций и методов для работы с линейной алгеброй. Это всё можно найти в под-модуле linalg. Этими модулями также можно оперировать с вырожденными и невырожденными матрицами. Определитель матрицы ищется таким образом:

In [240]:
a = np.array([[4, 2, 0], [9, 3, 7], [1, 2, 1]], float)
a

array([[4., 2., 0.],
       [9., 3., 7.],
       [1., 2., 1.]])

In [241]:
np.linalg.det(a)

-48.00000000000003

Также можно найти собственный вектор и собственное значение матрицы:

In [242]:
vals, vecs = np.linalg.eig(a)
print(vals)
print(vecs)

[ 8.85591316  1.9391628  -2.79507597]
[[-0.3663565  -0.54736745  0.25928158]
 [-0.88949768  0.5640176  -0.88091903]
 [-0.27308752  0.61828231  0.39592263]]


Невырожденная матрица может быть найдена так:

In [243]:
b = np.linalg.inv(a)
print(b)

array([[ 0.22916667,  0.04166667, -0.29166667],
       [ 0.04166667, -0.08333333,  0.58333333],
       [-0.3125    ,  0.125     ,  0.125     ]])

In [244]:
np.dot(a, b)

array([[1.00000000e+00, 5.55111512e-17, 0.00000000e+00],
       [0.00000000e+00, 1.00000000e+00, 2.22044605e-16],
       [0.00000000e+00, 1.38777878e-17, 1.00000000e+00]])

Одиночное разложение (аналог диагонализации не квадратной матрицы) может быть достигнут так:

In [245]:
a = np.array([[1, 3,4], [5, 2, 3]], float)
U, s, Vh = np.linalg.svd(a)
U

array([[-0.6113829 , -0.79133492],
       [-0.79133492,  0.6113829 ]])

In [246]:
s

array([7.46791327, 2.86884495])

In [247]:
Vh

array([[-0.61169129, -0.45753324, -0.64536587],
       [ 0.78971838, -0.40129005, -0.46401635],
       [-0.046676  , -0.79349205,  0.60678804]])